I'm sorry, but an uncaught exception occurred.

While running game code:
renpy.game.QuitException

During handling of the above exception, another exception occurred:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/ariellejoseph/Desktop/BIGBOSSGAME/busstopsimulator/game/saves/persistent.1760720891.tmp'

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "renpy/main.py", line 614, in main
    run(restart)
    ~~~^^^^^^^^^
  File "renpy/main.py", line 137, in run
    renpy.execution.run_context(True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "renpy/execution.py", line 1022, in run_context
    context.run()
    ~~~~~~~~~~~^^
  File "renpy/common/00start.rpy", line 282, in script
    python:
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/00start.rpy", line 284, in <module>
    renpy.call_in_new_context(_restart[2])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "renpy/game.py", line 372, in call_in_new_context
    return renpy.execution.run_context(False)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "renpy/execution.py", line 1022, in run_context
    context.run()
    ~~~~~~~~~~~^^
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "renpy/ast.py", line 1187, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1260, in py_exec_bytecode
    exec(bytecode, globals, locals)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
    ~~~~~~~~~~~^^
  File "renpy/ui.py", line 304, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/core.py", line 2219, in interact
    repeat, rv = self.interact_core(
                 ~~~~~~~~~~~~~~~~~~^
        preloads=preloads,
        ^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )  # type: ignore
    ^                
  File "renpy/display/core.py", line 3137, in interact_core
    self.quit_event()
    ~~~~~~~~~~~~~~~^^
  File "renpy/display/core.py", line 1813, in quit_event
    renpy.display.behavior.run(renpy.config.quit_action)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/behavior.py", line 411, in run
    return action(*args, **kwargs)
           ~~~~~~^^^^^^^^^^^^^^^^^
  File "renpy/common/00action_menu.rpy", line 274, in __call__
    renpy.quit(save=True)
    ~~~~~~~~~~^^^^^^^^^^^
  File "renpy/exports/restartexports.py", line 133, in quit
    raise renpy.game.QuitException(relaunch=relaunch, status=status)
renpy.game.QuitException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "renpy/bootstrap.py", line 376, in bootstrap
    renpy.main.main()
    ~~~~~~~~~~~~~~~^^
  File "renpy/main.py", line 626, in main
    renpy.persistent.update(True)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "renpy/persistent.py", line 461, in update
    save()
    ~~~~^^
  File "renpy/persistent.py", line 484, in save
    renpy.loadsave.location.save_persistent(compressed)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "renpy/savelocation.py", line 619, in save_persistent
    l.save_persistent(data)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "renpy/savelocation.py", line 427, in save_persistent
    with open(fn_tmp, "wb") as f:
         ~~~~^^^^^^^^^^^^^^      
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ariellejoseph/Desktop/BIGBOSSGAME/busstopsimulator/game/saves/persistent.1760720891.tmp'

macOS-15.6-arm64-arm-64bit arm64
Ren'Py 8.4.1.25072401
busstopsimulator 1.0
Fri Oct 17 13:34:11 2025
